NEWS/NEWS/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

NEWS/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("summernote/", include("django_summernote.urls")),
    path("news-admin/", include("dlog_app.urls")),
    path("", include("newspaper.urls")),
    path("accounts/login/", views.LoginView.as_view(), name="login"),
    path("accounts/logout/", views.LogoutView.as_view(), name="logout"),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dlog_app/urls.py
from django.urls import path

from dlog_app import views
app_name = "news_admin"

urlpatterns = [
    path("", views.PostListView.as_view(), name="post-list"),
    path("post-detail/<int:pk>/", views.PostDetailView.as_view(), name="post-detail"),
    path("draft-list/", views.DraftListView.as_view(), name="draft-list"),
    path("draft-detail/<int:pk>/", views.DraftDetailView.as_view(), name="draft-detail"),
    path("draft-publish/<int:pk>/", views.DraftPublishView.as_view() , name="draft-publish"),
    path("post-delete/<int:pk>/", views.PostDeleteView.as_view(), name="post-delete"),
    path("post-create/", views.PostCreateView.as_view(), name="post-create"),
    path("post-update/<int:pk>/", views.PostUpdateView.as_view(), name="post-update"),
]

templates/news_admin/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Personal Dlog</title>
  <link href="{% static 'news_admin/css/bootstrap.min.css' %}" rel="stylesheet" />
  <link rel="stylesheet"
    href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
  <link href="{% static 'news_admin/css/dlog.css' %}" rel="stylesheet" />
</head>

<body>
  <div class="page-header">
    {% if user.is_authenticated %}
    <a href="{% url 'logout' %}" class="top-menu">
      <span class="material-symbols-outlined lg-icons">logout</span>
    </a>

    <a href="{% url 'news_admin:post-create' %}" class="top-menu">
      <span class="material-symbols-outlined lg-icons">add</span>
    </a>

    <a href="{% url 'news_admin:draft-list' %}" class="top-menu">
      <span class="material-symbols-outlined lg-icons">draft</span>
    </a>
    {% else %}
    <a href="{% url 'login' %}" class="top-menu">
      <span class="material-symbols-outlined lg-icons">login</span>
    </a>
    {% endif %}



    <h1>
      <a href="/">
        <img src="{% static 'news_admin/img/favicon.ico' %}" alt="Personal Dlog" width="90px;" />
        Personal Dlog
      </a>
    </h1>
  </div>

  <div class="container">
    {% block content %}

    {% endblock content %}
  </div>

  <script src="{% static 'news_admin/js/bootstrap.bundle.min.js' %}"></script>
</body>

</html>

templates/news_admin/draft_detail.html
{% extends "news_admin/base.html" %}

{% block content %}
  <div class="row">
    <div class="col">
      <div class="post">
        <div class="mt-2">
          <a href="{% url 'news_admin:draft-publish' post.pk %}" class="btn btn-success">Publish</a>
        </div>
         
        <h1>
          <a href="">{{ post.title }}</a>
        </h1>
        <img src="{{ post.featured_image.url }}"
              alt="{{ post.title }}" 
              height="420px"
              width="860px0"
              class="mt-2-mb-2"/>
        <div class="mt-2 my-2">
          <a href="{% url 'news_admin:post-update' post.pk %}" class="btn btn-primary">Edit</a>
          <a href="{% url 'news_admin:post-delete' post.pk %}" class="btn btn-danger">Delete</a>
        </div>
        <div class="date author">@{{ post.author.username }}</div>
        <p>{{ post.content }}</p>
      </div>
    </div>
  </div>
{% endblock content %}

templates/news_admin/draft_list.html
{% extends "news_admin/base.html" %}

{% block content %}
  <div class="row">
    <div class="col">
      {% for post in posts %}
        <div class="post">
          <h1>
            <a href="{% url 'news_admin:draft-detail' post.pk %}">{{ post.title }}</a>
          </h1>
          <img src="{{ post.featured_image.url }}"
              alt="{{ post.title }}" 
              height="420px"
              width="860px0"
              class="mt-2-mb-2"/>
          <div class="date author">@{{ post.author.username }}</div>
          <p>
            {{ post.content|truncatechars:200 }} <a href="{% url 'news_admin:draft-detail' post.pk %}">View more</a>
          </p>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock content %}

templates/news_admin/post_create.html
{% extends "news_admin/base.html" %}

{% block content %}
   <form action="" 
         method="post"
         class="post-form"
         enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-success">Save</button>
   </form>
{% endblock content %}

templates/news_admin/post_detail.html
{% extends "news_admin/base.html" %}

{% block content %}
    <div class="row">
        <div class="col">
            <div class="post">
                <div class="date">{{ post.published_at }}</div>
                <img src="{{ post.featured_image.url }}" alt="{{ post.title }}" />
                <h1>
                    <a href="">{{ post.title }}</a>
                </h1>
                <img src="{{ post.featured_image.url }}"
                     alt="{{ post.title }}" 
                  height="420px"
                   width="860px0"
                   class="mt-2-mb-2"/>
                <div class="mt-2 my-2">
                    <a href="{% url 'news_admin:post-update' post.pk %}" 
                      class="btn btn-primary">Edit</a>
                    <a href="{% url 'news_admin:post-delete' post.pk %}"
                      class="btn btn-danger">Delete</a>
                </div>
                <div class="date author">@{{ post.author.username }}</div>
                <p>b {{ post.content|safe }}</p>
            </div>
        </div>
    </div>
{% endblock content %}

templates/news_admin/post_list.html
{% extends "news_admin/base.html" %}

{% block content %}
    <div class="row">
        <div class="col">
          {% for post in posts %}
            <div class="post">
                <div class="date">{{ post.published_at }}</div>
                <h1>
                    <a href="{% url 'news_admin:post-detail' post.pk %}">{{ post.title }}</a>
                </h1>
                <img src="{{ post.featured_image.url }}"
                     alt="{{ post.title }}" 
                     height="420px"
                     width="860px0"
                     class="mt-2-mb-2"/>
                <div class="date author">@{{ post.author.username }}</div>
                <p>
                    {{ post.content|truncatechars:200 }} <a href="{% url 'news_admin:post-detail' post.pk %}">View more</a>
                </p>
            </div>
          {% endfor %}
        </div>
    </div>
{% endblock content %}